# 🔗 Links:
# Source file: https://github.com/547daxia/expo-app-template/blob/master/.github/workflows/e2e-android-eas-build.yml
# End-to-end testing: https://starter.obytes.com/testing/end-to-end-testing/

# ✍️ Description:
# This workflow is used to run end-to-end tests for EAS build on Android.
# It downloads an APK from EAS and runs Maestro on a GitHub-hosted Android emulator.

# 🚨 GITHUB SECRETS REQUIRED: None

name: E2E Tests EAS Build Android (Maestro + Github Action)

on:
  workflow_dispatch:
    inputs:
      apk-url:
        type: string
        description: EAS APK URL
        required: true
        default: ''

jobs:
  download-eas-apk:
    if: github.event_name != 'pull_request'  && github.event.inputs.apk-url != ''
    name: Download Test APK From EAS Url (wget)
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Download EAS APK
        env:
          APK_URL: ${{ github.event.inputs.apk-url }}
        run: curl --fail --location --proto '=https' --output ./app-release.apk "$APK_URL"

      - name: Upload Test APK
        uses: actions/upload-artifact@v7
        with:
          name: test-apk
          path: ./app-release.apk

  test-android:
    name: E2E Tests EAS Build Android (Maestro + Github Action)
    needs: download-eas-apk
    runs-on: macos-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 📦 Install Maestro
        run: npm run install-maestro # # We use npm because we don't need to install deps again

      - name: Set Up JDK for Maestro
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: '17'

      - name: Download Test APK
        uses: actions/download-artifact@v8
        with:
          name: test-apk
          path: ${{ github.workspace }}

      - name: AVD cache
        uses: actions/cache@v5
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-avd-api-35

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          cores: 2
          ram-size: 4096M
          profile: pixel_6
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests with Maestro
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          cores: 2
          ram-size: 4096M
          profile: pixel_6
          script: |
            adb install "${{ github.workspace }}/app-release.apk"
            $HOME/.maestro/bin/maestro test .maestro/ --env=APP_ID=com.example.mobileapp.preview --format junit --output report.xml

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: e2e-test-logs
          path: ~/.maestro/tests/**/*

      - name: Store tests result
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: e2e_android_report
          if-no-files-found: warn
          path: |
            report.xml
