# 🔗 Links:
# Source file: https://github.com/547daxia/expo-app-template/blob/master/.github/workflows/new-github-release.yml
# Starter releasing process: https://starter.obytes.com/ci-cd/app-releasing-process/

# ✍️ Description:
# This workflow runs the required quality checks for a version tag before creating
# the corresponding GitHub release with generated release notes.

# 🚨 GITHUB SECRETS REQUIRED: None

name: New GitHub Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: New GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: 🔎 Type check
        run: pnpm run type-check

      - name: ✨ Lint
        run: pnpm run lint

      - name: 🧪 Run tests
        run: pnpm run test:ci

      - name: 🚑 Expo Doctor
        run: pnpm run doctor

      - name: 🚀 Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          draft: false
